# Generated by Django 2.2.6 on 2019-10-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('organizador', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('datainscricao', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
