# Generated by Django 2.2.7 on 2019-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='evento/'),
        ),
    ]
