# Generated by Django 2.2.7 on 2019-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_evento_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, default='/media/sonart.jpeg', null=True, upload_to='evento/'),
        ),
    ]
