# Generated by Django 2.2.7 on 2019-11-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20191118_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='evento/'),
        ),
    ]
