# Generated by Django 2.2.7 on 2019-11-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20191118_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='banner',
        ),
        migrations.AddField(
            model_name='evento',
            name='picture',
            field=models.ImageField(blank=True, upload_to='evento/'),
        ),
    ]
