# Generated by Django 2.2.7 on 2019-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20191118_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, default='evento/default.png', null=True, upload_to='evento/'),
        ),
    ]
