# Generated by Django 2.2.7 on 2019-12-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_auto_20191128_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='evento/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
